name: 打包并输出到gh-pages分支进行预览

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:
    name: 打包并部署
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 指定Node.js版本
        uses: actions/setup-node@v4
        with:
          node-version: 20

 

      - name: 部署到gh-pages分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # 确保路径正确
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
